pulibrary/repecwp

- Gemfile
- app/controllers/papers_controller.rb
- app/helpers/application_helper.rb
- app/views/papers/_form.html.erb
- app/views/papers/show.html.erb
> form fixes.

- Gemfile
- Gemfile.lock
@axamei Sorry, error in gemfile.
> broken gemfile

- config/routes.rb
@axamei There is probably a better to add the custom routes they need for the series rdf files. Perhaps those should in a yaml file rather than stored in the database. This will work for now.
> check to make sure series table exists.

- app/views/series/index.html.erb
@axamei Small change of file path for series rdf file. After merging run ```bundle exec cap staging deploy``` locally to make sure you can push to staging.
> Update the (not-real) RDF file path.

- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/archives/edit.html.erb
- app/views/archives/index.html.erb
- app/views/archives/show.html.erb
- app/views/papers/edit.html.erb
- app/views/papers/show.html.erb
- app/views/series/edit.html.erb
- app/views/series/index.html.erb
- app/views/series/show.html.erb
- config/deploy/production.rb
@axamei Tweaks to the show pages for series and paper.
> Control and link display cleanup.

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- app/views/series/index.html.erb
@axamei after this any new users need to be manually added. For this app we don't want to create them automatically.
> Users are no longer auto-created.

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/helpers/application_helper.rb
- app/views/archives/edit.html.erb
- app/views/archives/index.html.erb
- app/views/archives/new.html.erb
- app/views/archives/show.html.erb
- app/views/papers/edit.html.erb
- app/views/papers/index.html.erb
- app/views/papers/new.html.erb
- app/views/papers/show.html.erb
- app/views/pul-assets/_menu.html.erb
- app/views/series/edit.html.erb
- app/views/series/index.html.erb
- app/views/series/new.html.erb
- app/views/series/show.html.erb
- config/initializers/devise.rb
- spec/views/series/show.html.erb_spec.rb
Change all the links to use the current script loction
> Added a helper method to find the current script location

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- config/brakeman.ignore
> Adding breakman and updating postgres to 13

- .lando.yml
> Use postgres 13 for development

- Gemfile
- Gemfile.lock
- config/boot.rb
> Remove bootsnap

- .circleci/config.yml
- .tool-versions
Sibling PR: https://github.com/pulibrary/princeton_ansible/pull/3531
> Upgrade to node 16

- .circleci/config.yml
- .tool-versions
related to https://github.com/pulibrary/princeton_ansible/issues/3476
> I3476 staging update

- .circleci/config.yml
- .tool-versions
- Gemfile.lock
- config/initializers/assets.rb
Node upgrade as part of pulibrary/dacs_handbook#157
> Upgraded nodejs to 20.11.1

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/tables.js
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/pul-assets/_menu.html.erb
- spec/rails_helper.rb
- spec/views/pul-assets/_menu.html.erb_spec.rb
* Take Lux from a CDN, rather than adding it to sprockets, [using these instructions](https://github.com/pulibrary/lux-design-system/blob/main/docs/adding_lux.md#adding-lux-to-a-static-html-page-using-an-iife-file)
* Add `js: true` to view tests, and do the capybara configuration necessary to make it work.
> Use Lux instead of PUL Assets

- README.md
> Remove data migration information from README

- bearer.yml
Actual vulnerability was addressed in #158
Closes #139
> Remove bearer skip rule for addressed vulnerability

- .circleci/config.yml
> [#160] Add continuous deployment in circleci config

- .circleci/config.yml
We don't use node for this project anymore (as of #178).  But I forgot to remove it from CI at that time. :-)
> Remove node from circleci

- .circleci/config.yml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
For issue https://github.com/pulibrary/repecwp/issues/171
> add code coverage/coveralls/ci badges.

- app/views/layouts/application.html.erb
- public/404.html
- public/422.html
- public/500.html
> Add html lang attributes to error files and series listings home page
